1. Import the numpy package under the name np and Print the numpy version and the configuration 

In [7]:
import numpy as np
print(np.__version__)

1.19.5


2. Create a null vector of size 10

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create Simple 1-D array and check type and check data types in array

In [13]:
a=np.array([1,2,3])
print(a)
type(a)

[1 2 3]


numpy.ndarray

4. How to find number of dimensions, bytes per element and bytes of memory used?

In [28]:
import numpy as np
ar = np.array([[1, 2, 3], [4, 5, 6]])
print(ar)
print("Dimension",ar.ndim)
print("Total byte used",ar.nbytes)
print("Bytes per element",ar.size)

[[1 2 3]
 [4 5 6]]
Dimension 2
Total byte used 48
Bytes per element 6


5. Create a null vector of size 10 but the fifth value which is 1

In [32]:
ar=np.zeros(10)
print(ar)
ar[4]=1
print(ar)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


6. Create a vector with values ranging from 10 to 49

In [36]:
r=np.arange(10,50)
print(r)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


7. Reverse a vector (first element becomes last)

In [44]:
r=np.arange(10,21)
print("Ascending to Descending :",r)
print("Descending to Ascending",r[::-1])

Ascending to Descending : [10 11 12 13 14 15 16 17 18 19 20]
Descending to Ascending [20 19 18 17 16 15 14 13 12 11 10]


8. Create a 3x3 matrix with values ranging from 0 to 8

In [60]:
import numpy as np
r=np.arange(0,9)
#print(r)
print(r.reshape(3,3))


[[0 1 2]
 [3 4 5]
 [6 7 8]]


9.Create a 3x3 identity matrix

In [61]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

10.Find indices of non-zero elements from [1,2,0,0,4,0]

In [64]:
x = np.array([[1,2,0,0,4,0]])
print(np.nonzero(x))


(array([0, 0, 0]), array([0, 1, 4]))


11. Create a 3x3 array with random values

In [71]:
np.random.random((3,3,3))


array([[[0.88730118, 0.21577506, 0.42556357],
        [0.57615242, 0.24920017, 0.27223144],
        [0.40728839, 0.29280311, 0.87298771]],

       [[0.98602239, 0.16171677, 0.69354312],
        [0.7185537 , 0.9586538 , 0.98883862],
        [0.29528756, 0.76723104, 0.58051288]],

       [[0.47941747, 0.26541615, 0.26340824],
        [0.57933289, 0.62934439, 0.31174819],
        [0.15183506, 0.05851403, 0.58825495]]])

12.Create a 10x10 array with random values and find the minimum and maximum values

In [77]:
x=np.random.random((10,10,10))
print(x)
print("minimum value is :", x.min())
print("maximum value is :",x.max())


[[[4.93079864e-02 2.37256706e-01 1.14023549e-01 1.24171992e-01
   9.63649615e-01 4.32703440e-01 1.52107153e-01 5.05915351e-01
   3.45094201e-01 1.18066107e-02]
  [7.95975176e-01 6.93726341e-01 2.57016653e-01 4.60543326e-01
   4.44269902e-01 5.48400364e-01 8.07650816e-02 6.45672141e-01
   5.32832464e-01 1.42185722e-01]
  [3.88202157e-01 1.86481285e-01 7.92915036e-01 8.49435921e-02
   1.89828374e-01 1.83155466e-01 4.28453056e-01 7.53115968e-01
   7.18201964e-01 9.75971039e-01]
  [2.74879094e-01 6.12832417e-01 6.96630670e-01 5.71916935e-01
   8.31154147e-02 7.70878178e-01 1.92080701e-02 6.42313719e-01
   8.12545952e-01 3.22191303e-01]
  [5.38710002e-01 3.66169596e-01 8.72068596e-01 6.96259596e-01
   9.74895711e-01 5.75936764e-02 2.33267928e-01 5.47231422e-01
   8.18458775e-01 7.67902764e-02]
  [4.78240229e-01 1.59652524e-01 3.98188875e-01 6.51875510e-01
   6.33671076e-01 5.73012852e-01 2.29858543e-02 8.91632230e-01
   3.61759128e-01 6.06035861e-01]
  [6.90544707e-02 3.95356706e-01 9.40212

13. Create a random vector of size 30 and find the mean value

In [81]:
x=np.random.random((30))
print(x)

print("Mean is ", np.mean(x))

[0.48183552 0.1649644  0.73854102 0.41143148 0.0959471  0.81430601
 0.24300494 0.55914372 0.19970359 0.65855258 0.8391492  0.62355562
 0.41419683 0.01020419 0.1885431  0.69164325 0.51188015 0.91339608
 0.37767717 0.55356892 0.51000218 0.92471241 0.44116944 0.38406249
 0.07795595 0.10883128 0.07883763 0.42231634 0.04512614 0.43338933]
Mean is  0.43058826904443137


14. Create a 2d array with 1 on the border and 0 inside

In [90]:
x=np.ones((5,5))
x[1:4,1:4]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


15. How to add a border (filled with 0's) around an existing array? 

In [107]:
x=np.zeros((5,5))
x[1:4,1:4]=1
print(x)



[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


16.How to Accessing/Changing specific elements, rows, columns, etc in Numpy array? Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]
Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [110]:
p= np.array([[ 10,20,30,40,50,60,80],[70,90,101,111,122,113,144]])
print("Accessing Element 13 : ",p[1,5])
print("1st Row: ",p[0])
print("3rd Column:",p[0,2])
print(p[0,1:6:2])
p[1,5] = 20
print("Replace Element 13 : ",p[1,5])

Accessing Element 13 :  113
1st Row:  [10 20 30 40 50 60 80]
3rd Column: 30
[20 40 60]
Replace Element 13 :  20


17.How to Convert a 1D array to a 2D array with 2 rows

In [143]:

r=np.arange(10,20)
print(r)
print(r.reshape(2,5))



[10 11 12 13 14 15 16 17 18 19]
[[10 11 12 13 14]
 [15 16 17 18 19]]


18. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
Input: a = np.array([1,2,3])
Desired Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [146]:

a = np.array([1,2,3])
print(a)

a = np.append(np.repeat(a,3),np.tile(a,3))
print(a)

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


19. Write a program to show how Numpy taking less memory compared to Python List?

In [147]:
l = range(1000)
import sys
a = 10
print("Size of list : ", sys.getsizeof(a)*len(l))
a1 = np.arange(1000)
print("Size of numpy array : ", a1.size*a1.itemsize)


Size of list :  28000
Size of numpy array :  8000


20. Write a program to show how Numpy taking less time compared to Python List?


In [148]:
import time
import sys
size =1000000
l1 = range(size)
l2 = range(size)
n1 = np.arange(size)
n2 = np.arange(size)
start = time.time( )
res = [(x+y) for x,y in zip(l1,l2)]
print("Time take by List : ", (time.time()-start)*1000)
start = time.time( )
res1 = n1+n2
print("Time taken by numpy array : ", (time.time()-start)*1000)

Time take by List :  132.60722160339355
Time taken by numpy array :  3.255128860473633
